/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Stylized Cottage
*/

import { CabinIsland } from '@/components/scene/part/CabinIsland';
import { PlaneBeach } from '@/components/scene/part/Plane';
import { TheatreObject } from '@/components/scene/TheatreObject';

export function ContactIsland() {
  return (
    <>
      <TheatreObject
        id="Contact: Base Island"
        position={[0, -1, 0]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <PlaneBeach position={[0, -1, 0]} rotation={[0, 90, 0]} />
      </TheatreObject>
      <TheatreObject
        id="Contact: Cabin Base"
        position={[0, -1, 0]}
        rotation={[0, Math.PI / 2, 0]} // 90 derajat = PI/2
      >
        <CabinIsland />
      </TheatreObject>
    </>
  );
}
