/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Stylized Cottage
*/

import { Cottage } from '@/components/scene/part/Cottage';
import { PlaneBeach } from '@/components/scene/part/Plane';
import { TheatreObject } from '@/components/scene/TheatreObject';

export function HomeIsland() {
  return (
    <>
      <TheatreObject
        id="Home: Beach Base"
        position={[0, -1, 0]}
        rotation={[0, Math.PI / 2, 0]} // 90 derajat = PI/2
      >
        <PlaneBeach position={[0, -1, 0]} rotation={[0, 90, 0]} />
      </TheatreObject>
      <TheatreObject
        id="Home: Cottage Home"
        position={[0, -1, 0]}
        rotation={[0, Math.PI / 2, 0]} // 90 derajat = PI/2
      >
        <Cottage />
      </TheatreObject>
    </>
  );
}
