/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Low poly Abandoned Fountain with Rune Stones
*/

import type * as THREE from 'three';
import type { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

// Definisi Tipe untuk Nodes dan Materials agar TypeScript tidak error
type GLTFResult = GLTF & {
  nodes: {
    pCube6_Foutain_0: THREE.Mesh;
    pCylinder2_low1_Foutain_0: THREE.Mesh;
    pCube3_low1_Foutain_0: THREE.Mesh;
    tru2_low_Foutain_0: THREE.Mesh;
    tru1_low_Foutain_0: THREE.Mesh;
    pCube3_low_Foutain_0: THREE.Mesh;
    pCube1_low_Foutain_0: THREE.Mesh;
    tru3_low_Foutain_0: THREE.Mesh;
    pCylinder1_low_Foutain_0: THREE.Mesh;
    pCube4_low_Foutain_0: THREE.Mesh;
    pCylinder2_low_Foutain_0: THREE.Mesh;
    tree_low_Foutain_0: THREE.Mesh;
    pCube2_low_Foutain_0: THREE.Mesh;
    pCube5_low4_Foutain_0: THREE.Mesh;
    pCube2_low2_Foutain_0: THREE.Mesh;
    pCube2_low1_Foutain_0: THREE.Mesh;
    tree_low1_Foutain_0: THREE.Mesh;
    pCube5_low5_Foutain_0: THREE.Mesh;
    pCube5_low6_Foutain_0: THREE.Mesh;
    pCube4_low1_Foutain_0: THREE.Mesh;
  };
  materials: {
    Foutain: THREE.MeshStandardMaterial; // Typo 'Foutain' bawaan dari file 3D aslinya
  };
};

export function Abandoned(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/3d/rune_stones.glb',
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null} scale={0.2} position={[0, 5, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube6_Foutain_0.geometry}
        material={materials.Foutain}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder2_low1_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube3_low1_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tru2_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tru1_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube3_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube1_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[1.3, 6.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tru3_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder1_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube4_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[-0.4, -0.1, -0.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder2_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube2_low_Foutain_0.geometry}
        material={materials.Foutain}
        position={[-1.2, 8.2, 1.6]}
        rotation={[0, 0, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube5_low4_Foutain_0.geometry}
        material={materials.Foutain}
        position={[-23, 0, -7]}
        rotation={[0, -0.4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube2_low2_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube2_low1_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_low1_Foutain_0.geometry}
        material={materials.Foutain}
        position={[0, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube5_low5_Foutain_0.geometry}
        material={materials.Foutain}
        position={[-4.3, 0, 8.3]}
        rotation={[0, 0.7, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube5_low6_Foutain_0.geometry}
        material={materials.Foutain}
        position={[1.4, 0, 16.9]}
        rotation={[0, -1.2, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube4_low1_Foutain_0.geometry}
        material={materials.Foutain}
        position={[-1.1, -0.1, -0.3]}
        rotation={[-Math.PI, -1.5, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/3d/rune_stones.glb');
