/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/** biome-ignore-all lint/suspicious/noExplicitAny: <noExplicitAny> */

import { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
// 1. IMPORT PENTING
import { useGraph } from '@react-three/fiber';
import { SkeletonUtils } from 'three-stdlib';
import type * as THREE from 'three';

export function AnneCharacter(props: any) {
  const group = useRef<THREE.Group>(null);

  // Load file GLB asli
  const { scene, materials, animations } = useGLTF('/3d/Anne.glb') as any;

  // 2. LOGIC CLONING (WAJIB ADA)
  // Ini membuat copy baru dari model setiap kali komponen ini dipasang
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  // 3. AMBIL NODES DARI HASIL CLONE (BUKAN DARI 'scene' ASLI)
  const { nodes } = useGraph(clone);

  const { actions } = useAnimations(animations, group);

  // Play Animasi Default (Idle)
  useEffect(() => {
    // Ambil nama animasi pertama yg tersedia
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      actions[actionNames[7]]?.reset().fadeIn(0.5).play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="Cube117"
            // 4. GUNAKAN NODES DARI CLONE
            geometry={(nodes.Cube117 as THREE.SkinnedMesh).geometry}
            material={materials.AtlasMaterial}
            skeleton={(nodes.Cube117 as THREE.SkinnedMesh).skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/Anne.glb');
