/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';

export function BatuKecil(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d/batu_kecil.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[-11.774, -1.788, -7.852]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_72 as THREE.Mesh).geometry}
          material={materials.RocksSmall}
          position={[0, 0, 7.988]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/3d/batu_kecil.glb');
