/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/** biome-ignore-all lint/suspicious/noExplicitAny: <noExplicitAny> */
/** biome-ignore-all lint/style/noNonNullAssertion: <noNonNullAssertion> */

import { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useGraph, useFrame } from '@react-three/fiber';
import { SkeletonUtils } from 'three-stdlib';
import type * as THREE from 'three';

export function BirdAnimated(props: any) {
  const group = useRef<THREE.Group>(null);

  // 1. Load Model & Clone (Ini sudah benar untuk SkinnedMesh)
  const { scene, materials, animations } = useGLTF('/3d/seagull_animated.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  // 2. Setup Animasi
  // PENTING: Kita akan update mixer secara manual agar bisa dikontrol (Throttling)
  const { actions } = useAnimations(animations, group);

  // Randomize start time agar kepakan sayap tidak serentak robotik
  useEffect(() => {
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      const action = actions[actionNames[0]];
      action?.reset().fadeIn(0.5).play();
      // Set waktu acak
      action!.time = Math.random() * 2;
      // Variasi kecepatan kepak sayap (0.8x sampai 1.2x)
      action!.timeScale = 0.8 + Math.random() * 0.4;
    }
  }, [actions]);

  // 3. OPTIMASI ANIMASI: Update Mixer dengan 'delta' tapi dibatasi
  // Jika burung jauh, kita bisa skip update animasi (Culling)

  useFrame((state, _delta) => {
    // Jarak kamera ke burung (Squared distance lebih cepat)
    if (group.current) {
      const distSq = state.camera.position.distanceToSquared(
        group.current.position,
      );

      // Jika burung sangat jauh (> 150 unit), matikan animasi (hemat CPU drastis)
      // 150 * 150 = 22500
      if (distSq > 22500) {
        return;
      }
    }

    // Jika dekat, biarkan useAnimations mengurusnya (default behavior)
    // Tapi karena kita pakai useAnimations hook, dia sudah auto-update.
    // Triknya: Kita matikan auto-update Drei dan update manual jika perlu optimization lebih dalam.
    // Untuk sekarang, Culling jarak di atas sudah cukup membantu.
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        >
          <group
            name="b8e0a8d2290944cc82d96cf3c33c11dafbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  {/* Gunakan frustumCulled={true} pada mesh agar GPU skip render jika diluar layar */}
                  <skinnedMesh
                    frustumCulled={true}
                    geometry={(nodes.Object_7 as THREE.SkinnedMesh).geometry}
                    material={materials.lambert5}
                    skeleton={(nodes.Object_7 as THREE.SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    frustumCulled={true}
                    geometry={(nodes.Object_8 as THREE.SkinnedMesh).geometry}
                    material={materials.lambert4}
                    skeleton={(nodes.Object_8 as THREE.SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    frustumCulled={true}
                    geometry={(nodes.Object_9 as THREE.SkinnedMesh).geometry}
                    material={materials.lambert2}
                    skeleton={(nodes.Object_9 as THREE.SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    frustumCulled={true}
                    geometry={(nodes.Object_10 as THREE.SkinnedMesh).geometry}
                    material={materials.lambert3}
                    skeleton={(nodes.Object_10 as THREE.SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    frustumCulled={true}
                    geometry={(nodes.Object_11 as THREE.SkinnedMesh).geometry}
                    material={materials.lambert6}
                    skeleton={(nodes.Object_11 as THREE.SkinnedMesh).skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/seagull_animated.glb');
