/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTFResult } from '@/types/GLTFResult';

export function CabinIsland(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/3d/contact-island.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[32.286, 15.018, -15.847]}
          rotation={[-1.707, -0.661, 0.69]}
          scale={9.445}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane051_derevo_krona5_0.geometry}
            material={materials.derevo_krona5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane051_derevo_krona6_0.geometry}
            material={materials.derevo_krona6}
          />
        </group>
        <group
          position={[23.7, 65.577, -16.479]}
          rotation={[0.632, -1.072, -0.216]}
          scale={9.079}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane089_derevo_krona1_0.geometry}
            material={materials.derevo_krona1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane089_derevo_krona2_0.geometry}
            material={materials.derevo_krona2}
          />
        </group>
        <group
          position={[-28.635, 2.463, 10.665]}
          rotation={[-2.923, -0.442, -2.182]}
          scale={3.506}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane305_derevo_krona7png_0.geometry}
            material={materials['derevo_krona7.png']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane305_derevo_krona8png_0.geometry}
            material={materials['derevo_krona8.png']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_most_0.geometry}
          material={materials.most}
          position={[61.626, -27.542, -0.049]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_dom_0.geometry}
          material={materials.material}
          position={[0.097, 7.137, 3.326]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_zemlia_0.geometry}
          material={materials.zemlia}
          position={[-5.702, -7.35, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_zemlia2_0.geometry}
          material={materials.zemlia2}
          position={[-5.702, -7.35, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_stvol_dereva_0.geometry}
          material={materials.stvol_dereva}
          position={[-33.68, 40.551, -34.685]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_bochka_0.geometry}
          material={materials.bochka}
          position={[-20.303, 4.805, -15.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_iashik_krishka_0.geometry}
          material={materials.iashik_krishka}
          position={[-24.477, 3.493, -10.127]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_elka_krona4_0.geometry}
          material={materials.elka_krona4}
          position={[-4.105, 156.493, -63.304]}
          rotation={[-2.32, 0.067, -3.103]}
          scale={[1.432, 5.284, 10.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_grass1_0.geometry}
          material={materials.grass1}
          position={[37.802, -14.162, -0.878]}
          rotation={[-0.011, 0.098, -0.053]}
          scale={1.577}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_elka_krona3_0.geometry}
          material={materials.elka_krona3}
          position={[-26.119, 173.419, -32.594]}
          rotation={[-0.918, -0.297, -0.281]}
          scale={[1.432, 5.284, 10.019]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/3d/contact-island.glb');
