/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, type JSX, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import type * as THREE from 'three';
import { useGraph } from '@react-three/fiber';
import { SkeletonUtils } from 'three-stdlib';

export function CaptainCharacter(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { scene, materials, animations } = useGLTF('/3d/Pirate_Captain.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Ambil nama animasi pertama yg tersedia
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      actions[actionNames[8]]?.reset().fadeIn(0.5).play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="Captain_Barbarossa_"
            geometry={(nodes.Captain_Barbarossa_ as THREE.SkinnedMesh).geometry}
            material={materials.AtlasMaterial}
            skeleton={(nodes.Captain_Barbarossa_ as THREE.SkinnedMesh).skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <skinnedMesh
            name="Ernest"
            geometry={(nodes.Ernest as THREE.SkinnedMesh).geometry}
            material={materials.AtlasMaterial}
            skeleton={(nodes.Ernest as THREE.SkinnedMesh).skeleton}
            position={[0.6, 0.9, -0.4]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/Pirate_Captain.glb');
