/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Stylized Cottage
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'react';
import type * as THREE from 'three';

export function Cottage(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d/cottage.glb');

  return (
    <group {...props} dispose={null}>
      <group position={[0, -1, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_4 as THREE.Mesh).geometry}
          material={materials.Stylized_cottage_material}
          scale={0.3}
          position={[0, 0, 0]}
          rotation={[0, 110, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/3d/cottage.glb');
