/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTFResult } from '@/types/GLTFResult';

export function PlaneBeach(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/3d/plane.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.barile_5004_BARILE_0.geometry}
            material={materials['BARILE.001']}
            position={[-394.627, 275.615, 46.686]}
            rotation={[1.367, -0.19, -0.565]}
            scale={24.377}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.barile_5005_BARILE_0.geometry}
            material={materials['BARILE.001']}
            position={[-551.025, 228.526, -420.086]}
            rotation={[0.462, 0.401, 1.234]}
            scale={24.377}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.barile_5006_BARILE_0.geometry}
            material={materials['BARILE.001']}
            position={[123.246, 247.26, -517.303]}
            rotation={[-2.783, 0.56, -1.419]}
            scale={24.377}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bottiglia_vetro_0.geometry}
            material={materials['vetro.001']}
            position={[-169.66, 138.238, 239.514]}
            rotation={[-2.341, -0.406, -0.196]}
            scale={22.085}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brocca_vetro_0.geometry}
            material={materials['vetro.001']}
            position={[-504.721, 266.003, 788.355]}
            rotation={[-1.501, -0.148, 0.016]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brocca001_vetro_0.geometry}
            material={materials['vetro.001']}
            position={[-458.359, 261.05, 819.078]}
            rotation={[-1.464, 0.008, -0.018]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brocca002_vetro_0.geometry}
            material={materials['vetro.001']}
            position={[-649.456, 235.755, -59.326]}
            rotation={[-1.5, -0.247, 0.023]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brocca003_vetro_0.geometry}
            material={materials['vetro.001']}
            position={[106.959, 276.999, -710.798]}
            rotation={[-1.502, -0.01, 0.007]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.calice_legno_0.geometry}
            material={materials['legno.001']}
            position={[-60.44, 228.456, -313.87]}
            rotation={[-2.681, -0.436, 0.158]}
            scale={7.441}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.calice001_legno_0.geometry}
            material={materials['legno.001']}
            position={[-399.948, 310.673, 49.949]}
            rotation={[-1.635, -0.13, 0.263]}
            scale={7.441}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassa_2_cassa_0.geometry}
            material={materials['cassa.001']}
            position={[-509.567, 268.251, -181.292]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10.31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassa_2001_cassa_0.geometry}
            material={materials['cassa.001']}
            position={[-837.556, 187.145, -414.152]}
            rotation={[-1.731, -0.248, 0.083]}
            scale={10.31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassa_4_cassa_0.geometry}
            material={materials['cassa.001']}
            position={[203.16, 90.322, -172.094]}
            rotation={[-1.533, 0.174, 0.158]}
            scale={10.31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassa_5_cassa_0.geometry}
            material={materials['cassa.001']}
            position={[6.898, 274.427, -761.045]}
            rotation={[-1.824, 0.233, 0.108]}
            scale={10.31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cocco_legno_0.geometry}
            material={materials['legno.001']}
            position={[-262.185, 752.849, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_scrigno_0.geometry}
            material={materials['scrigno.001']}
            position={[-385.751, 258.311, 564.277]}
            rotation={[-1.62, 0.222, -1.836]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_legno_0.geometry}
            material={materials['legno.001']}
            position={[223.47, 167.215, -379.331]}
            rotation={[-1.077, 0.305, -0.02]}
            scale={31.812}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_paglia_0.geometry}
            material={materials.paglia}
            position={[-445.842, 314.851, 681.93]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={88.039}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_paglia_0.geometry}
            material={materials.paglia}
            position={[264.686, 301.052, -718.828]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={91.934}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-505.935, 295.558, 518.987]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2002_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-318.076, 422.039, 4.015]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={63.938}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2003_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-781.904, 340.449, -372.355]}
            rotation={[0.151, 0.298, 1.658]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2004_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-214.857, 393.663, -514.391]}
            rotation={[0.531, 0.092, 1.311]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2005_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-642.276, 326.224, -783.838]}
            rotation={[0, 0.535, Math.PI / 2]}
            scale={42.517}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.palma_2006_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-738.362, 319.333, 223.317]}
            rotation={[-3.134, 0.367, -1.618]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_foglie_0.geometry}
            material={materials['foglie.001']}
            position={[-475.981, 266.387, 42.684]}
            rotation={[-1.609, 0.153, -0.052]}
            scale={60.952}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-2.121, 0.157, 1.977]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-Math.PI / 2, -0.561, -2.924]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane009_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-Math.PI / 2, 0.456, 0]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane010_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-1.087, 0.148, -0.077]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane011_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-1.935, 0.163, 0.032]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-1.005, 0.141, -0.089]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-579.123, 565.153, 617.723]}
            rotation={[-2.223, 0.095, -0.341]}
            scale={45.164}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane021_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-Math.PI / 2, -0.665, -2.924]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane022_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-2.115, 0.068, 1.923]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane023_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-Math.PI / 2, 0.352, 0]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane024_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-1.092, 0.056, -0.029]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane025_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 778.281, 49.873]}
            rotation={[-1.93, 0.067, -0.005]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane026_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-1.01, 0.053, -0.033]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane027_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-268.228, 779.433, 21.647]}
            rotation={[-2.22, 0.013, -0.404]}
            scale={66.781}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane028_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-0.791, -0.093, -1.502]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane029_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.627, -0.502, -3.027]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane030_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.795, 0.077, 1.413]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane031_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.419, 0.499, 1.374]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane032_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.581, -0.323, 1.359]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane033_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.4, 0.579, 1.364]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane034_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[16.34, 634.963, -274.988]}
            rotation={[-1.591, -0.617, 0.944]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-0.978, 0.32, -0.916]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane036_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-1.335, -0.5, -2.213]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane037_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-1.877, -0.177, 2.079]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane038_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-1.88, 0.376, 2.15]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane039_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-632.951, 563.111, -827.902]}
            rotation={[-1.441, -0.343, 2.112]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane040_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-1.929, 0.444, 2.169]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane041_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-649.096, 563.877, -818.33]}
            rotation={[-1.214, -0.554, 1.801]}
            scale={44.407}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane042_foglie_0.geometry}
            material={materials['foglie.001']}
            position={[-698.039, 234.09, 721.344]}
            rotation={[-1.635, -0.073, -0.271]}
            scale={60.952}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane043_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-0.858, 0.086, -1.054]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane044_foglie_0.geometry}
            material={materials['foglie.001']}
            position={[-32.913, 274.495, -642.749]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={60.952}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane045_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.39, -0.654, -2.479]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane046_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.838, -0.206, 1.805]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane047_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.69, 0.327, 1.866]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane048_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.453, -0.477, 1.855]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane049_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.716, 0.405, 1.875]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane050_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-654.506, 706.024, -250.236]}
            rotation={[-1.276, -0.733, 1.546]}
            scale={61.878}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane051_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-2.725, 0.321, 1.602]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane052_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-1.77, 0.617, -0.123]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane053_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-1.736, 0.017, -1.94]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane054_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-2.175, -0.329, -1.94]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane055_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-1.864, 0.451, -1.991]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane056_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-2.207, -0.405, -1.951]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane057_ATLASPALMA001_0.geometry}
            material={materials['ATLASPALMA.002']}
            position={[-824.417, 573.967, 151.831]}
            rotation={[-1.772, 0.735, -2.453]}
            scale={45.237}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sass05001_legno_0.geometry}
            material={materials['legno.001']}
            position={[-216.908, 132.205, 289.774]}
            rotation={[-2.043, 0.104, -0.363]}
            scale={48.627}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sasso_legno_0.geometry}
            material={materials['legno.001']}
            position={[-147.842, 315.626, -648.633]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sasso_2_legno_0.geometry}
            material={materials['legno.001']}
            position={[-303.629, 268.397, -674.673]}
            rotation={[-Math.PI / 2, 0, 0.611]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sasso001_legno_0.geometry}
            material={materials['legno.001']}
            position={[-756.923, 263.001, 340.774]}
            rotation={[-1.69, -0.278, -0.025]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spiaggia_Material_0.geometry}
            material={materials['Material.015']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/plane.glb');
