/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/** biome-ignore-all lint/correctness/useExhaustiveDependencies: <useExhaustiveDependencies> */
/** biome-ignore-all lint/style/noNonNullAssertion: <noNonNullAssertion> */
/** biome-ignore-all lint/suspicious/noExplicitAny: <noExplicitAny> */

import { useRef, useEffect, useMemo, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { useGameStore } from '@/stores/useGameStore';

type SharkState = 'follow' | 'orbit' | 'eat';

export function Shark(props: any) {
  const group = useRef<THREE.Group>(null);

  // --- STORE REFERENCES ---
  const boatPositionRef = useGameStore((state) => state.boatPositionRef);
  const boatRotationRef = useGameStore((state) => state.boatRotationRef);
  const boatSpeedRef = useGameStore((state) => state.boatSpeedRef); // Butuh speed buat tahu kapan berhenti
  const collectedIds = useGameStore((state) => state.collectedIds); // Butuh ini buat trigger makan

  const { nodes, materials, animations } = useGLTF('/3d/Shark.glb') as any;
  const { actions, names } = useAnimations(animations, group);

  // --- INTERNAL STATE ---
  const [currentState, setCurrentState] = useState<SharkState>('orbit');

  // Refs untuk logic tanpa re-render
  const isJumping = useRef(false);
  const jumpTime = useRef(0);
  const orbitAngle = useRef(0);

  // Vector Reusable (Hemat Memori)
  const targetPos = useMemo(() => new THREE.Vector3(), []);
  const tempVec = useMemo(() => new THREE.Vector3(), []);
  const lookAtTarget = useMemo(() => new THREE.Vector3(), []);

  // --- 1. ANIMATION CONTROLLER ---
  useEffect(() => {
    // Mapping Animasi sesuai request:
    // Index 0: Makan/Loncat (Animasi ke-1)
    // Index 1: Follow/Jalan (Animasi ke-2)
    // Index 2: Orbit/Idle (Animasi ke-3)

    const playAnimation = (index: number, speed = 1) => {
      // Stop semua animasi dulu dengan fadeOut
      names.forEach((name) => {
        actions[name]?.fadeOut(0.5);
      });

      // Play animasi target
      const actionName = names[index];
      if (actionName && actions[actionName]) {
        const action = actions[actionName];
        action!.reset().fadeIn(0.5).play();
        action!.timeScale = speed;
      }
    };

    if (currentState === 'eat') {
      playAnimation(0, 1.5); // Animasi 1 (Makan) - Lebih cepat
    } else if (currentState === 'follow') {
      playAnimation(1, 1.2); // Animasi 2 (Jalan)
    } else {
      playAnimation(2, 0.8); // Animasi 3 (Idle/Orbit) - Santai
    }
  }, [currentState, actions, names]);

  // --- 2. TRIGGER MAKAN (LISTENER) ---
  // Mendeteksi perubahan jumlah collectedIds
  useEffect(() => {
    if (collectedIds.length > 0) {
      triggerJump();
    }
  }, [collectedIds.length]);

  const triggerJump = () => {
    if (isJumping.current) return; // Jangan trigger kalau lagi loncat

    isJumping.current = true;
    jumpTime.current = 0;
    setCurrentState('eat');

    // Reset ke state normal setelah 1.5 detik (durasi loncat)
    setTimeout(() => {
      isJumping.current = false;
      // State akan di-handle otomatis oleh useFrame logic di bawah (follow/orbit)
    }, 1500);
  };

  // --- 3. GAME LOOP (USE FRAME) ---
  useFrame((state, delta) => {
    if (!group.current || !boatPositionRef.current) return;

    const boatPos = boatPositionRef.current;
    const boatRot = boatRotationRef.current;
    const speed = boatSpeedRef.current || 0;
    const isMoving = speed > 0.5; // Anggap bergerak kalau speed > 0.5

    // --- STATE UPDATE (Kecuali lagi makan) ---
    if (!isJumping.current) {
      if (isMoving && currentState !== 'follow') {
        setCurrentState('follow');
      } else if (!isMoving && currentState !== 'orbit') {
        setCurrentState('orbit');
      }
    }

    // --- LOGIC POSISI BERDASARKAN STATE ---

    if (isJumping.current) {
      // === KASUS 3: MAKAN (JUMP) ===
      jumpTime.current += delta * 8; // Kecepatan animasi loncat

      // Gerakan Parabola Loncat (Sinus 0 -> PI)
      // Naik cepat, turun cepat
      const jumpHeight = Math.sin(Math.min(jumpTime.current, Math.PI)) * 4;

      // Hiu sedikit maju ke depan kapal seolah menyambar koin
      tempVec.set(5, 0, 5).applyQuaternion(boatRot);
      targetPos.copy(boatPos).add(tempVec);
      targetPos.y = -1 + jumpHeight; // Base Y + Tinggi loncat

      // Hiu menghadap ke atas saat naik, ke bawah saat turun
      group.current.position.lerp(targetPos, delta * 3);

      // LookAt logic khusus jump (ke atas)
      lookAtTarget.copy(targetPos).add(new THREE.Vector3(0, 0, 0));
      group.current.lookAt(lookAtTarget);
    } else if (isMoving) {
      // === KASUS 1: FOLLOW (BELAKANG KAPAL) ===

      // Posisi di belakang kapal (Z: -12), agak di bawah (-2)
      tempVec.set(0, 0, -10).applyQuaternion(boatRot);
      targetPos.copy(boatPos).add(tempVec);

      // Tambah efek ombak dikit
      targetPos.y += Math.sin(state.clock.elapsedTime * 3) * 0.2;

      // Gerakan Smooth Lerp mengejar kapal
      group.current.position.lerp(targetPos, delta * 3);

      // Rotasi mengikuti rotasi kapal
      group.current.quaternion.slerp(boatRot, delta * 3);
    } else {
      // === KASUS 2: ORBIT (MEMUTARI KAPAL) ===

      // Update sudut putaran
      orbitAngle.current += delta * 0.5; // Kecepatan putar
      const radius = 10; // Jari-jari putaran

      // Hitung posisi lingkaran
      const x = Math.sin(orbitAngle.current) * radius;
      const z = Math.cos(orbitAngle.current) * radius;

      // Posisi relatif terhadap kapal
      targetPos.set(boatPos.x + x, -1, boatPos.z + z); // Y = -2 (Bawah air)

      // Update Posisi
      group.current.position.lerp(targetPos, delta * 2);

      // Hiu Selalu Menghadap Arah Gerakan Orbit (Tangent)
      // Kita intip posisi hiu sedikit di masa depan untuk LookAt
      const nextAngle = orbitAngle.current + 0.1;
      const nextX = Math.sin(nextAngle) * radius;
      const nextZ = Math.cos(nextAngle) * radius;
      lookAtTarget.set(boatPos.x + nextX, -1, boatPos.z + nextZ);

      group.current.lookAt(lookAtTarget);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="SharkArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
            <primitive object={nodes.Abdomen} />
            <primitive object={nodes.Center} />
          </group>
          <skinnedMesh
            name="Shark"
            geometry={nodes.Shark.geometry}
            material={materials.AtlasMaterial}
            skeleton={nodes.Shark.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            castShadow
          />
          <skinnedMesh
            name="Shark001"
            geometry={nodes.Shark001.geometry}
            material={materials.AtlasMaterial}
            skeleton={nodes.Shark001.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            castShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/Shark.glb');
