/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTFResult } from '@/types/GLTFResult';

export function TropicalIsland(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/3d/tropical.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.28, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials['BeachBaked.001']}
          position={[0, 0, 3.272]}
          scale={0.5}
        />
      </group>
      <group
        position={[2.076, 0.016, -1.778]}
        rotation={[1.544, -0.079, -2.333]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials['Palme.001']}
          position={[-8.35, -2.825, 0.661]}
          rotation={[-0.035, -0.014, -0.687]}
        />
      </group>
      <group
        position={[5.64, 3.269, 5.868]}
        rotation={[-3.137, -0.584, -3.103]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials['Palme_Blaetter.001']}
          position={[-0.517, -0.391, -0.2]}
          rotation={[0.007, 0.686, -0.049]}
        />
      </group>
      <group
        position={[-0.019, -1.968, 0]}
        rotation={[Math.PI, -0.788, Math.PI]}
        scale={0.518}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials['RocksBig.001']}
        position={[1.64, -2.196, 12.346]}
      />
    </group>
  );
}

useGLTF.preload('/3d/tropical.glb');
